'use strict';
// All story branches are authored fiction; this prototype makes no remote model calls.
const KEY='becoming-me-v1';
const STAGES=[
 {age:8,name:'家庭',title:'今天，谁可以先玩？',scene:'周六下午，窗外有人叫你去画画。\n桌上留着没收的碗，小一点的表弟还在等人陪。',question:'如果暂时不必向谁解释，你想怎么度过下午？',speaker:'妈妈，在出门上班以前',voice:'「你比较懂事，帮我照看一下。忙完了再玩，好不好？」',context:{thin:'家里请不起额外的照护。妈妈的下一班工作不能迟到。',buffer:'家里可以请人临时照看，但大人已经习惯先叫你的名字。'},options:[
  {title:'去画那棵树',wish:'把想画的东西画完。',gain:'你留下了第一幅自己喜欢的画。',cost:'妈妈临时找人接手，也向你表达了失望。',thin:'你出门前先拜托邻居帮忙，欠下的人情被反复提起。',buffer:'家里请了临时照护。你仍要解释，为什么画画值得这个下午。',author:'“懂事”的奖励，让照护看起来像你天生的职责。',tag:'家庭 · 性别化的照护期待'},
  {title:'留下来陪表弟',wish:'陪他，也许本来就是我想做的。',gain:'你们一起编了一个只有两个人知道的故事。',cost:'等你有空时，窗外那片光已经消失。',thin:'你的时间填补了家里付不起的那一份照护。',buffer:'这一次是你自愿留下；下一次，大人却未必还会问。',author:'照顾也可以出于爱。问题是：你是否一直拥有拒绝的余地？',tag:'家庭 · 爱与责任'},
  {title:'提出轮流照看',wish:'我想被照顾，也愿意照顾别人。',gain:'你第一次为自己的时间提出条件。',cost:'协商占去了半个下午，也没有立刻换来理解。',thin:'所有人的时间都很紧，轮流的约定还得等下一周。',buffer:'家里同意找人分担，但有人说你越来越“不省心”。',author:'公平不是一句口号，它也需要有人、有时间来接手。',tag:'家庭 · 分工与可用资源'}
 ]},
 {age:17,name:'学校',title:'把未来填进一个格子。',scene:'志愿表上有三个空格。\n美术老师说你有观察力，班主任说你的成绩适合报一个“稳一点”的专业。',question:'先不考虑录取、学费和别人的评价，你想学什么？',speaker:'家人，在志愿截止前一晚',voice:'「我们不是不支持你。只是怕你以后太辛苦。」',context:{thin:'家里能承担普通学费，但额外的作品集培训和异地生活，需要你打工补上。',buffer:'学费和异地生活有家里支持，但支持也附带了“别让我们失望”的期待。'},options:[
  {title:'去学视觉艺术',wish:'试试把看见的东西变成作品。',gain:'你开始用图像表达自己。',cost:'职业路径不再有一个很容易解释的名字。',thin:'你一边做兼职一边准备作品集，睡眠和创作时间开始竞争。',buffer:'你有了一段安心试错的时间，但每次汇报近况都像在证明投入值得。',author:'同样一句“追求热爱”，背后的试错预算可能完全不同。',tag:'学校 · 阶层与试错成本'},
  {title:'选择有清晰职业路径的专业',wish:'我也向往可靠、有秩序的生活。',gain:'你能看见一条较清楚的就业路线。',cost:'画画变成要从课业里另外挤出的时间。',thin:'较可预测的开销让家人松了口气，你也暂时放下了经济上的焦虑。',buffer:'生活更符合家人的预期；你开始分辨，安稳是谁的愿望。',author:'稳定本身不是错误。值得问的是，你有没有看见其他路径。',tag:'学校 · 风险与教育期待'},
  {title:'先读一年，再申请转向',wish:'我需要更多信息，才能替未来决定。',gain:'你给自己保留了重新判断的机会。',cost:'转专业的门槛仍然存在，延期也会增加开销。',thin:'你提前查了转专业规则，又给自己列了一张兼职计划。',buffer:'家庭能负担延期，你仍需要说服学校和家人接受这次绕路。',author:'“以后再选”也是一种选择，但未来的门不一定一直开着。',tag:'学校 · 制度与路径依赖'}
 ]},
 {age:24,name:'工作',title:'会议结束后，还剩一件事。',scene:'你和同事一起完成了一个项目。\n新的机会来了：一个能被看见的提案，以及一份没人主动认领的协调工作。',question:'在这份工作里，你现在最想争取什么？',speaker:'主管，散会以后',voice:'「你沟通细，又让人放心。客户协调还是你来吧？」',context:{thin:'你刚攒下一点应急金，房租和给家里的补贴每月都要支出。',buffer:'你的生活暂时有缓冲，可以承担一段工作关系不稳定的时间。'},options:[
  {title:'争取做提案负责人',wish:'让我的想法被看见。',gain:'你获得了介绍自己方案的机会。',cost:'你需要公开争取资源，也可能遭遇否定。',thin:'你保留现有岗位，一边额外准备提案。这份机会先消耗了你的休息。',buffer:'你拒绝了一部分杂务，把精力放在方案上；同事并不都认同。',author:'表达野心并不自动换来机会，评价标准和资源分配也在起作用。',tag:'工作 · 可见度与评价权'},
  {title:'把协调工作做好',wish:'我喜欢让一群人顺利合作。',gain:'团队因为你的协调少了很多摩擦。',cost:'成果可能被归到团队名下，难以体现在个人晋升中。',thin:'熟悉的职责让收入更可预期，但工作量慢慢超过岗位说明。',buffer:'你有余地享受合作本身，也开始要求把这项贡献写进考核。',author:'维护关系是劳动。喜欢它，不意味着它可以一直不被计价。',tag:'工作 · 不可见劳动'},
  {title:'要求轮岗与明确署名',wish:'希望分工可以说清楚。',gain:'一部分隐形劳动被写到了台面上。',cost:'讨论暂时没有结论，有人觉得你把事情复杂化了。',thin:'你先邀请同事一起提出建议，避免一个人承担全部风险。',buffer:'你能承受谈判失败，但还需要同事愿意共同改变规则。',author:'把问题说出来是开始；规则改变通常还需要集体支持。',tag:'工作 · 制度与协同行动'}
 ]},
 {age:29,name:'亲密关系',title:'两个人的未来，写在哪里？',scene:'伴侣收到另一座城市的工作邀请。\n你在这里刚刚建立了自己的合作网络。两张地图被摊在同一张桌上。',question:'此刻你真正向往的是哪一种生活？',speaker:'伴侣，认真地商量',voice:'「我们总要有一个人调整。我也怕错过这次机会。」',context:{thin:'两地房租和频繁往返，会明显压缩你们的储蓄。',buffer:'你们能暂时负担两地生活，但金钱不能补上所有缺席的日常。'},options:[
  {title:'一起去新的城市',wish:'我想和这个人一起生活。',gain:'你们继续分享具体的日常。',cost:'你需要在陌生地方重新建立工作和朋友网络。',thin:'你先找一份能覆盖房租的工作，原来的计划向后挪了。',buffer:'你有时间寻找合适的机会，也需要面对暂时依赖对方的感觉。',author:'为爱迁移可以是主动选择。关键是调整的责任是否总落在同一边。',tag:'关系 · 流动与机会成本'},
  {title:'留在这里，尝试异地',wish:'我想守住正在长出来的生活。',gain:'你保留了自己的工作和支持网络。',cost:'关系需要承受距离、不确定与额外沟通。',thin:'你们减少见面次数，把有限的钱留给重要的往返。',buffer:'你们可以常见面，但没法预订彼此每一次需要陪伴的时刻。',author:'独立不等于不需要他人；坚持也可能伴随真实的失落。',tag:'关系 · 自主与依恋'},
  {title:'谈一个六个月的共同计划',wish:'我不想一个人替两个人做决定。',gain:'你们把各自的损失和愿望一起摊开。',cost:'临时安排有期限，到时仍可能无法两全。',thin:'你们列出费用上限，约定双方轮流承担往返。',buffer:'你们有条件尝试更多安排，但必须持续协商，而不是等待问题自己消失。',author:'协商需要对等的发言权，也需要让安排真正可执行的条件。',tag:'关系 · 共同决策'}
 ]},
 {age:35,name:'此刻',title:'那个空出来的星期六。',scene:'你终于有了一个没有被安排的下午。\n手机里，有家人的消息、朋友的邀约，还有一个很久没打开的创作文件夹。',question:'如果这个下午只属于你，你想把它交给什么？',speaker:'你自己，或者那些已经住进心里的声音',voice:'「我是不是应该先做一点有用的事？」',context:{thin:'这周你已经很累。休息、兼职和关系都在等待同一段时间。',buffer:'这次你可以暂时放下生计。但“不能浪费时间”的感觉并没有一起消失。'},options:[
  {title:'重新打开创作文件夹',wish:'我想继续那个未完成的东西。',gain:'作品只多了一小部分，但你重新感到了投入。',cost:'一些消息没有及时回复，家务也还在那里。',thin:'你把创作限定在两小时内，给接下来的工作留一点体力。',buffer:'你允许自己没有产出地试了很久，仍偶尔想向别人证明这段时间值得。',author:'热爱也可能被变成新的绩效。它是否允许你暂时做得不好？',tag:'此刻 · 生产力的内化'},
  {title:'去见一个想念的人',wish:'有些连接，是我自己想维系的。',gain:'你们好好说了一次话。',cost:'独处和创作需要另找一个时间。',thin:'你们选了不用花钱的散步，承认彼此最近都有些吃力。',buffer:'你把手机放到一边，不再急着把这次见面变成一个“有效安排”。',author:'关系不全是外界的束缚，它也可以是你主动选择的自我组成。',tag:'此刻 · 连接与主体性'},
  {title:'今天，什么都不证明',wish:'我只想休息。',gain:'身体慢慢放松了下来。',cost:'事情并没有消失，内疚也没有立即停止。',thin:'你给兼职消息设了晚一点的提醒，这次停下仍有具体的经济成本。',buffer:'你拥有休息的空间，开始练习不为它寻找一个正当理由。',author:'休息不该是奖励；但不同的人，能停下来的条件并不相同。',tag:'此刻 · 时间与休息权'}
 ]}
];
const $=s=>document.querySelector(s), app=$('#app');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={screen:'home',background:'thin',step:0,wish:null,records:[],revealed:false,rewrite:null,reflection:'',userPhrase:'',customOption:null,quick:false};
let resume=null;
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw && ['thin','buffer'].includes(raw.background) && Array.isArray(raw.records) && raw.records.length<=5 && raw.records.every((r,i)=>r.step===i&&Number.isInteger(r.wish)&&r.wish>=0&&r.wish<3&&Number.isInteger(r.actual)&&r.actual>=0&&r.actual<3)){resume={...state,...raw,reflection:String(raw.reflection||'').slice(0,160),rewrite:raw.rewrite&&Number.isInteger(raw.rewrite.step)&&raw.rewrite.step>=0&&raw.rewrite.step<raw.records.length&&Number.isInteger(raw.rewrite.option)&&raw.rewrite.option>=0&&raw.rewrite.option<3?raw.rewrite:null};}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));resume=JSON.parse(JSON.stringify(state));}catch{notify('浏览器未允许本地存储；本次体验仍可继续。');}}
function notify(t){$('#notice').textContent=t;$('#notice').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').style.display='none',3500);}
function transition(){render();window.scrollTo({top:0,behavior:'instant'});const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function artwork(){return `<div class="art"><svg viewBox="0 0 560 560" role="img" aria-label="一张人形纸片，被家庭、体面、懂事和期待的红线牵引，其中一根线正在断开"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#b8b5a8" stroke-width=".45"/></pattern><pattern id="words" width="130" height="65" patternUnits="userSpaceOnUse"><text x="0" y="18" fill="#e8e4d7" font-size="10" font-family="serif">应该 懂事 安稳</text><text x="12" y="45" fill="#e8e4d7" font-size="10" font-family="serif">以后 别人 为你好</text></pattern><clipPath id="person"><path d="M274 147c-48-1-49 70-18 86l-8 25-48 20-66 129 28 13 69-89-12 190 133 0-24-191 64 78 28-25-67-107-48-18-9-26c38-18 26-84-22-85z"/></clipPath></defs><path fill="url(#grid)" d="M28 28h504v494H28z"/><circle cx="280" cy="280" r="185" fill="none" stroke="#b8b5a8" stroke-width=".8" stroke-dasharray="2 7"/><circle cx="280" cy="280" r="135" fill="none" stroke="#c7c2b5" stroke-width=".7"/><path d="M280 30v490M28 280h500" stroke="#b8b5a8" stroke-width=".6"/><g fill="#807b70" font-size="9" letter-spacing="2"><text x="37" y="48">SUBJECT / 001</text><text x="390" y="48">NOT YET WRITTEN</text></g><g stroke="#b73527" stroke-width="1.3" fill="none"><path d="M126 113L259 278M431 135L307 274M88 290L151 401M418 431L328 467M270 64L276 147"/><path d="M421 253l-21 37m-10 19-5 9"/></g><g fill="#b73527"><circle cx="126" cy="113" r="3"/><circle cx="431" cy="135" r="3"/><circle cx="88" cy="290" r="3"/><circle cx="418" cy="431" r="3"/></g><g font-family="serif" font-size="19" fill="#b73527"><text x="50" y="104" transform="rotate(-8 50 104)">要懂事</text><text x="425" y="122" transform="rotate(9 425 122)">为你好</text><text x="33" y="278">别任性</text><text x="408" y="463" transform="rotate(-8 408 463)">有用的人</text></g><g clip-path="url(#person)"><path fill="#30342f" d="M110 130h340v410H110z"/><path fill="url(#words)" opacity=".23" d="M110 130h340v410H110z"/><path d="M180 370l200-24v35l-200 26z" fill="#ece8dd"/><text x="253" y="383" fill="#b73527" font-size="24" font-family="serif" transform="rotate(-7 253 383)">我</text></g><g fill="none" stroke="#b73527" stroke-width="1.6"><path d="M408 285l27 6m-22 6 21-16"/><path d="M434 267q32-29 56-5"/></g><text x="432" y="245" font-size="13" fill="#b73527" font-family="serif">也可以松开</text><text x="40" y="546" font-size="10" fill="#807b70" letter-spacing="2">FIG. 01 — A SELF IN THE MAKING</text></svg><div class="art-caption"><span>人的轮廓 / 尚未定稿</span><span class="red">不是命运图谱</span></div></div>`;}
function renderHome(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">AN INTERACTIVE ESSAY ON BECOMING</div><h1>成为<br><span>自己。</span></h1><div class="handwritten">（谁写下了我的选择？）</div><p class="intro">你会长大，会做选择，会被夸奖“懂事”。<br>直到有一天，你翻到人生的背面——<br>才发现，那里还有别人的笔迹。</p><button class="primary" data-action="prologue">开始这一生 <span>↗</span></button>${resume&&resume.records.length?'<button class="text-btn" data-action="resume">继续上次的人生</button>':''}<div class="meta"><span>约 5—7 分钟</span><span>五个人生切片</span><span>一次重新落笔</span></div></div>${artwork()}</section><div class="hero-bottom"><strong>你以为是“我的选择”，<br>有多少其实是别人替你写好的？</strong><div>先听见自己的心愿，再走进现实的条件。<br>最后，把人生翻到背面。这里没有理想人格，也没有通关分数。<br>只有一个尚未结束的问题：我还想把什么，写回自己的手里？</div></div>`;}
function renderPrologue(){app.innerHTML=`<section class="prologue"><div class="eyebrow red">序章 / 00 岁 · 出生</div><h1>你还没学会说“我”，<br>世界已经开始称呼你。</h1><p>这一次，你走进“林”的生活：一个在县城长大的女性。你将经历从童年到成年的五个虚构切片。这是一个具体处境的文学实验，不代表所有女性，也不推断你的身份。</p><p>先为这个故事选择一组条件。起点不是人格，却会改变同一选择的代价。</p><div class="backdrop-options"><button data-action="background" data-value="thin" class="${state.background==='thin'?'selected':''}" aria-pressed="${state.background==='thin'}"><b>需要自己兜底</b>家人关心你，但能提供的经济支持有限。意外和试错，需要从自己的时间里支付。</button><button data-action="background" data-value="buffer" class="${state.background==='buffer'?'selected':''}" aria-pressed="${state.background==='buffer'}"><b>拥有一些缓冲</b>家里可以支持一段试错。经济压力小一些，情感义务与外界期待依然存在。</button></div><div class="ai-seed"><label for="seed">给 AI 一句话：我真正想保留的是……</label><textarea id="seed" maxlength="70" placeholder="例如：我想保留周末画画的时间，也想照顾好家人。">${escapeHTML(state.userPhrase||'')}</textarea><small>这句话只在本机处理，用来生成一条“第四选项”和结尾边注。AI 可能误读你，你可以随时修改。</small></div><p class="small-label">选择会保存在本机浏览器；不上传。可在创作手记中删除。${resume&&resume.records.length?'开始新的人生会替换本机上次的进度。':''}</p><div class="start-row"><button class="primary" data-action="start">让故事开始 <span>→</span></button><button class="secondary" data-action="quick">3 分钟评委模式</button></div></section>`;}
function progress(){return `<ol class="progress" aria-label="故事进度">${STAGES.map((s,i)=>`<li class="${i===state.step?'active':i<state.step?'done':''}" ${i===state.step?'aria-current="step"':''}>0${i+1}<span>${s.name} / ${s.age} 岁</span></li>`).join('')}</ol>`;}
function optionList(s){const list=s.options.slice();if(state.customOption&&s===STAGES[0])list.push(state.customOption);return list;}
function optionAt(s,i){return optionList(s)[i]||s.options[0];}
function generateCustomOption(){const phrase=(state.userPhrase||'').trim();if(!phrase)return null;const title=/家|父母|照顾|陪/.test(phrase)?'让照护不再只落在我身上':/画|写|创作|做梦|想要/.test(phrase)?'为这件想做的事留出时间':/爱|关系|朋友|伴侣/.test(phrase)?'把重要的关系带进决定里':/钱|工作|稳定|学/.test(phrase)?'先创造一个可以试错的缓冲':'把这句话留给自己';return {title,wish:'我想保留：'+phrase.slice(0,48),gain:'你把一句还没有位置的话，放进了人生选项。',cost:'这条路没有现成的模板，需要你和别人一起协商条件。',thin:'你先从一件可执行的小事开始，把愿望拆成可以被支持的请求。',buffer:'你有空间试一次，但仍要面对“这值得吗”的反复追问。',author:'这是由你的原话生成的第四个选项。AI 只负责翻译，决定权仍在你手里。',tag:'用户输入 · 可被修改的愿望'};}
function choices(s,mode){const opts=optionList(s);return `<div class="choices">${opts.map((o,i)=>`<button class="choice ${i===3?'ai-choice':''}" data-action="${mode}" data-value="${i}"><b>${i===3?'✦':String.fromCharCode(65+i)}</b><span><strong>${o.title}</strong><small>${mode==='wish'?o.wish:mode==='rewrite-option'?o.gain:'我决定这样做。'}${i===3?'<em>AI 边注</em>':''}</small></span></button>`).join('')}</div>`;}
function renderScene(){const s=STAGES[state.step],rec=state.records[state.step];let body='';if(state.screen==='wish'){body=`<div class="phase">第一遍 · 只问心愿</div><h2 class="question">${s.question}</h2>${choices(s,'wish')}<p class="small-label">先别急着权衡。接下来，你会看见现实里的条件。</p>`;}else if(state.screen==='choice'){body=`<div class="phase">第二遍 · 把现实放回画面</div><div class="wish-record">刚才，你想要的是<br><strong>${optionAt(s,state.wish).wish}</strong></div><div class="voice"><label>${s.speaker}</label><p>${s.voice}</p><small>${s.context[state.background]}</small></div><h2 class="question">现在，你会怎么做？</h2>${choices(s,'actual')}`;}else{const o=optionAt(s,rec.actual);body=`<div class="phase">这一页 · 你确实走过</div><div class="aftermath"><h2>${o.title}</h2><p>${o[state.background]}</p><div class="tradeoff"><div><label>你得到的</label>${o.gain}</div><div><label>你也承担着</label>${o.cost}</div></div><p class="transition-note">${rec.wish===rec.actual?'这次，你的心愿和行动站在了同一边。<br>它仍然不是一个没有代价的选择。':'这次，你走向了和最初心愿不同的方向。<br>改变心意，不等于失去自己。'}</p><button class="primary" data-action="next">${state.step===4?'把人生翻到背面':'继续长大'} <span>→</span></button></div>`;}app.innerHTML=`<section class="scene phase-${["family","school","work","intimacy","now"][state.step]} ${state.quick?"quick-mode":""}">${state.quick?"<div class=\"demo-badge\">评委 Demo · 3 分钟模式</div>":""}${progress()}<div class="scene-layout"><aside class="chapter"><div class="eyebrow">LIFE FRAGMENT / 0${state.step+1}</div><div class="age">${s.age}<small>岁 / ${s.name}</small></div><h1>${s.title}</h1><p>${s.scene}</p><div class="chapter-art">人生档案 / 林<br>起点：${state.background==='thin'?'需要自己兜底':'拥有一些缓冲'}<br>你不是在找最优解。你正在留下自己的笔迹。</div></aside><div>${body}</div></div></section>`;}
function renderEnding(){const same=state.records.filter(r=>r.wish===r.actual).length;app.innerHTML=`<section class="ending"><div class="eyebrow red">THE OTHER SIDE / 人生的背面</div><h1>${state.revealed?'原来，一直不止<br>我一个人在落笔。':'这五次选择，<br>真的是我一个人写的吗？'}</h1><p class="ending-intro">五个时刻里，有 ${same} 次心愿与行动相遇。这个数字不是“做自己”的分数：顺从可能出于爱，坚持也可能出于对成功的焦虑。我们把两者并排放在这里，留给你自己读。</p>${!state.revealed?'<button class="primary reveal-button" data-action="reveal">显影：看见选项背后的字 <span>↗</span></button>':'<p class="small-label">红字是作品提出的一种结构性阅读，不是对你动机的判决。点击任意一页，可以试着改写。</p>'}<div class="ledger ${state.revealed?'unmasked revealing':''}"><div class="ledger-head"><span>时刻</span><span>最初的心愿</span><span>现实中的选择</span><span>选项背后的字</span></div>${state.records.map(r=>{const s=STAGES[r.step],o=optionAt(s,r.actual);return `<div class="ledger-row"><div class="stage">${s.name}<small>${s.age} 岁</small></div><div class="wish">${optionAt(s,r.wish).title}</div><div class="actual">${o.title}</div><div class="margin-note">${state.revealed?`${o.author}<br><small>↳ ${o.tag}</small><br><button data-action="rewrite" data-value="${r.step}">改写这一页 ↗</button>`:'<span class="hidden-author" aria-label="尚未显影的文字"></span>'}</div></div>`;}).join('')}</div>${state.rewrite?rewritePanel():''}${state.revealed?`<div class="reflection"><div><div class="phase">下一页 / 尚未发生</div><h2>如果选项里没有我想要的，<br>我可以自己写一个吗？</h2><p>你不必永远在“接受”和“离开”之间作答。也许你需要的是一个愿意分担的人、一条允许回头的规则，或者一次不必解释的休息。</p><p>回看刚才：你想改的是自己的决定，还是让决定如此艰难的条件？</p></div><div><label for="reflection" class="small-label">写下你想增加的第四个选项（可留空）</label><textarea id="reflection" maxlength="160" placeholder="我希望，在要求我变得勇敢之前……">${escapeHTML(state.reflection)}</textarea><div class="end-actions"><button class="primary" data-action="export">带走这一页 <span>↓</span></button><button class="secondary" data-action="save">留在本机</button></div><p class="small-label">导出为图片；不上传，不生成心理标签。</p></div></div><div class="rule"></div><div class="end-actions"><button class="secondary" data-action="prologue">换一组起点，再走一次</button><button class="text-btn" data-action="about">阅读创作手记与书籍联系 ↗</button></div>`:''}</section>`;}
function rewritePanel(){const {step,option}=state.rewrite,s=STAGES[step],before=optionAt(s,state.records[step].actual),after=optionAt(s,option);return `<section class="counterfactual" id="counterfactual"><div class="phase">另一种可能 / ${s.age} 岁</div><h2>换一种选择，未必换来一个完美人生。</h2><div class="comparison"><div><label>你原来写下的</label><h3>${before.title}</h3><p>${before[state.background]}</p><p>得到：${before.gain}<br>代价：${before.cost}</p></div><div><label>你重新写下的</label><h3>${after.title}</h3><p>${after[state.background]}</p><p>得到：${after.gain}<br>代价：${after.cost}</p></div></div><p class="red">你愿意为这种结果承担代价吗？又有哪些代价，本来就不该只由你承担？</p><p class="boundary">这是同一时刻的反事实叙事，不是命运预测。后面的经历没有被自动重算；原来的笔迹也被保留下来。你可以重新改写任意一页。</p></section>`;}
function render(){if(state.screen==='home')renderHome();else if(state.screen==='prologue')renderPrologue();else if(state.screen==='ending')renderEnding();else renderScene();}
function showDialog(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
function showAbout(){showDialog(`<div class="eyebrow red">ARTIST'S NOTE / 创作手记</div><h2>成为自己，不是一道单选题。</h2><p>这部互动叙事从一个问题出发：如果我选择了自己想要的生活，为什么仍然可能失落？作品把“愿望—条件—行动—代价”分开，让主体性与社会结构同时进入画面。</p><h3>与两本书的对话</h3><p>西蒙娜·德·波伏瓦《第二性》启发了作品关于“成为”、处境与主体性的追问；上野千鹤子《厌女》启发了作品对性别规范及其内化的观察。这里的情节和句子均为原创虚构，不是原书引文，也不声称概括两本书的全部观点。</p><p>作品不把女性写成一种统一命运，也不把照护、稳定或亲密关系自动视作错误。林只是一个有限的叙事视角。阶层起点改变了资源与成本，不能据此预测任何真实个体。</p><h3>这一版如何工作</h3><p>当前为 AI 辅助制作的本地互动作品：五个阶段、十五个手写选项、两组资源条件。情节由预先编写的分支呈现，没有接入实时生成模型。声音为浏览器合成，图像为原创代码绘制。没有云端公共社区，也没有虚构其他参与者的数据。</p><p>选择仅保存在本机；导出图片由本机完成。如果用于公开展览，应让参与者自己决定是否展示其结尾文字。</p><h3>参赛定位</h3><p>建议主报创新互动内容赛道；书籍可视化是思想来源与后续可选定位，能否兼报需以主办方实际规则为准。本原型未使用 Eazo 开发，尚不符合海报列出的 Eazo 特别奖工具条件。</p><div class="rule"></div><button class="secondary" data-action="clear">删除本机进度与文字</button>`);}
function doRewrite(step){const s=STAGES[step],r=state.records[step];showDialog(`<div class="eyebrow red">REWRITE / ${s.age} 岁 · ${s.name}</div><h2>如果再给你一次落笔的机会。</h2><p>当时你最想：${optionAt(s,r.wish).title}。<br>后来你选择：${optionAt(s,r.actual).title}。</p><p>现实条件仍然存在：${s.context[state.background]}</p><div class="choices">${s.options.map((o,i)=>i===r.actual?'':`<button class="choice" data-action="rewrite-option" data-step="${step}" data-value="${i}"><b>↗</b><span><strong>${o.title}</strong><small>看一看这一条路得到什么，又要付出什么。</small></span></button>`).join('')}</div>`);}
let audio=null,soundOn=false;
async function toggleSound(){try{if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();const ctx=new AC(),gain=ctx.createGain();gain.gain.value=0;gain.connect(ctx.destination);[130.81,196,261.63].forEach((f,i)=>{const o=ctx.createOscillator(),v=ctx.createGain();o.frequency.value=f;o.type='sine';v.gain.value=[.45,.18,.10][i];o.connect(v).connect(gain);o.start();});audio={ctx,gain};}await audio.ctx.resume();soundOn=!soundOn;audio.gain.gain.setTargetAtTime(soundOn?.055:0,audio.ctx.currentTime,.3);$('#sound').textContent='声音 '+(soundOn?'开':'关');$('#sound').setAttribute('aria-pressed',String(soundOn));}catch{notify('当前浏览器无法启用声音，你可以继续无声体验。');}}
function playCue(stage,kind){if(!audio||!soundOn)return;const ctx=audio.ctx,o=ctx.createOscillator(),g=ctx.createGain();const base=[146.83,196,220,164.81,130.81][stage]||160;o.type=kind==='wish'?'triangle':'sine';o.frequency.setValueAtTime(base*(kind==='wish'?1:0.75),ctx.currentTime);o.frequency.exponentialRampToValueAtTime(base*(kind==='wish'?1.5:0.5),ctx.currentTime+.35);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.6);o.connect(g).connect(audio.ctx.destination);o.start();o.stop(ctx.currentTime+.65);}
document.addEventListener('visibilitychange',()=>{if(audio)audio.gain.gain.setTargetAtTime(soundOn&&!document.hidden?.055:0,audio.ctx.currentTime,.15);});
function exportPage(){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1640;const c=canvas.getContext('2d');c.fillStyle='#ece8dd';c.fillRect(0,0,1200,1640);c.strokeStyle='#bcb7a9';c.strokeRect(55,55,1090,1530);c.fillStyle='#b73527';c.font='18px sans-serif';c.fillText('BECOMING / ME     一页尚未定稿的人生',90,110);c.fillStyle='#252624';c.font='72px serif';c.fillText('成为自己。',90,230);c.font='25px serif';c.fillText('那些落在我人生上的笔迹，我开始认得了。',90,295);c.font='18px sans-serif';c.fillStyle='#706e65';c.fillText('虚构角色：林  /  '+(state.background==='thin'?'需要自己兜底':'拥有一些缓冲'),90,349);let y=417;for(const r of state.records){const s=STAGES[r.step];c.fillStyle='#b73527';c.font='21px serif';c.fillText(`${s.age} 岁 / ${s.name}`,90,y);c.fillStyle='#252624';c.font='24px serif';c.fillText(optionAt(s,r.actual).title,290,y);c.fillStyle='#706e65';c.font='17px sans-serif';c.fillText('心愿：'+optionAt(s,r.wish).title,290,y+34);c.strokeStyle='#cbc5b9';c.beginPath();c.moveTo(90,y+58);c.lineTo(1110,y+58);c.stroke();y+=99;}
 c.fillStyle='#b73527';c.font='19px sans-serif';c.fillText(state.rewrite?'我重新落笔的地方':'下一页，尚未发生',90,969);c.fillStyle='#252624';c.font='27px serif';if(state.rewrite){const r=state.rewrite;c.fillText(`${STAGES[r.step].age} 岁：${optionAt(STAGES[r.step],r.option).title}`,90,1020);}else c.fillText('我可以给自己增加一个新的选项。',90,1020);c.font='29px serif';const text=state.reflection.trim()||'我想改的，是我的选择，还是让选择如此艰难的条件？';let line='',yy=1110;for(const ch of text){if(ch==='\n'||c.measureText(line+ch).width>990){c.fillText(line,90,yy);yy+=46;line=ch==='\n'?'':ch;}else line+=ch;}if(line)c.fillText(line,90,yy);c.fillStyle='#706e65';c.font='17px sans-serif';c.fillText('互动叙事 · 原创虚构 · 无人格评分与命运预测',90,1500);c.fillText('不是每一笔都由我起头。但下一笔，可以重新商量。',90,1536);canvas.toBlob(blob=>{if(!blob){notify('图片导出失败，请再试一次。');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='成为自己-我的下一页.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),20000);notify('已生成你的书页图片。');},'image/png');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,n=Number(b.dataset.value);if(action==='about'){showAbout();return;}if(action==='prologue'){state.screen='prologue';transition();return;}if(action==='background'){state.background=b.dataset.value;renderPrologue();return;}if(action==='start'){state={screen:'wish',background:state.background,step:0,wish:null,records:[],revealed:false,rewrite:null,reflection:''};persist();transition();return;}if(action==='resume'){state=JSON.parse(JSON.stringify(resume));if(state.records.length===5)state.screen='ending';else{state.step=state.records.length;state.screen='wish';state.wish=null;}transition();return;}if(action==='wish'){state.wish=n;state.screen='choice';transition();return;}if(action==='actual'){state.records.push({step:state.step,wish:state.wish,actual:n});state.screen='aftermath';persist();transition();return;}if(action==='next'){if(state.step===4)state.screen='ending';else{state.step++;state.wish=null;state.screen='wish';}persist();transition();return;}if(action==='reveal'){state.revealed=true;persist();transition();return;}if(action==='rewrite'){doRewrite(n);return;}if(action==='rewrite-option'){state.rewrite={step:Number(b.dataset.step),option:n};$('#dialog').close();persist();renderEnding();$('#counterfactual').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});return;}if(action==='save'||action==='export'){state.reflection=$('#reflection').value.slice(0,160);persist();if(action==='export')exportPage();else notify('已保存在本机浏览器。');return;}if(action==='clear'){try{localStorage.removeItem(KEY);}catch{}resume=null;state={screen:'home',background:'thin',step:0,wish:null,records:[],revealed:false,rewrite:null,reflection:''};$('#dialog').close();transition();notify('本机进度与文字已删除。');}});
document.addEventListener('input',e=>{if(e.target.id==='reflection')state.reflection=e.target.value.slice(0,160);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="quick"]');if(!b)return;state.quick=true;state.userPhrase=(($('#seed')&&$('#seed').value)||state.userPhrase||'').slice(0,70);state.customOption=generateCustomOption();state.screen='wish';state.step=0;state.wish=null;state.records=[];persist();transition();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="start"]');if(!b)return;state.userPhrase=(($('#seed')&&$('#seed').value)||state.userPhrase||'').slice(0,70);state.customOption=generateCustomOption();state.quick=false;persist();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='wish'||a==='actual'||a==='reveal'||a==='next')playCue(state.step,a==='wish'?'wish':'actual');});
$('#about').addEventListener('click',showAbout);$('#sound').addEventListener('click',toggleSound);$('#dialog .close').addEventListener('click',()=>$('#dialog').close());
render();






