'use strict';

const STORAGE_KEY = 'be-myself-game-v2';
const app = document.querySelector('#app');
const dialog = document.querySelector('#dialog');
const dialogContent = document.querySelector('#dialog-content');
const toast = document.querySelector('#toast');
const stageColors = ['#a84936', '#6d5a98', '#3f6f72', '#9a4d67', '#b63a2b'];

const STAGES = [
  {age:8,name:'家庭',title:'今天，谁可以先玩？',scene:'周六下午，窗外有人叫你去画画。\n桌上留着没收的碗，小一点的表弟还在等人陪。',question:'如果暂时不必向谁解释，你想怎么度过下午？',speaker:'妈妈，在出门上班以前',voice:'「你比较懂事，帮我照看一下。忙完了再玩，好不好？」',context:{thin:'家里请不起额外的照护。妈妈的下一班工作不能迟到。',buffer:'家里可以请人临时照看，但大人已经习惯先叫你的名字。'},options:[
    {title:'去画那棵树',wish:'把想画的东西画完。',gain:'你留下了第一幅自己喜欢的画。',cost:'妈妈临时找人接手，也向你表达了失望。',thin:'你出门前先拜托邻居帮忙，欠下的人情被反复提起。',buffer:'家里请了临时照护。你仍要解释，为什么画画值得这个下午。',author:'“懂事”的奖励，让照护看起来像你天生的职责。',tag:'家庭 · 性别化的照护期待'},
    {title:'留下来陪表弟',wish:'陪他，也许本来就是我想做的。',gain:'你们一起编了一个只有两个人知道的故事。',cost:'等你有空时，窗外那片光已经消失。',thin:'你的时间填补了家里付不起的那一份照护。',buffer:'这一次是你自愿留下；下一次，大人却未必还会问。',author:'照顾也可以出于爱。问题是：你是否一直拥有拒绝的余地？',tag:'家庭 · 爱与责任'},
    {title:'提出轮流照看',wish:'我想被照顾，也愿意照顾别人。',gain:'你第一次为自己的时间提出条件。',cost:'协商占去了半个下午，也没有立刻换来理解。',thin:'所有人的时间都很紧，轮流的约定还得等下一周。',buffer:'家里同意找人分担，但有人说你越来越“不省心”。',author:'公平需要有人、有时间来接手。',tag:'家庭 · 分工与可用资源'}]},
  {age:17,name:'学校',title:'把未来填进一个格子。',scene:'志愿表上有三个空格。\n美术老师说你有观察力，班主任说成绩适合报一个“稳一点”的专业。',question:'先不考虑录取、学费和别人的评价，你想学什么？',speaker:'家人，在志愿截止前一晚',voice:'「我们不是不支持你。只是怕你以后太辛苦。」',context:{thin:'普通学费可以承担，额外的作品集培训和异地生活需要你打工补上。',buffer:'学费和异地生活有支持，但支持也附带了“别让我们失望”的期待。'},options:[
    {title:'去学视觉艺术',wish:'试试把看见的东西变成作品。',gain:'你开始用图像表达自己。',cost:'职业路径不再有一个容易解释的名字。',thin:'你一边兼职一边准备作品集，睡眠和创作时间开始竞争。',buffer:'你有一段安心试错的时间，但每次汇报都像在证明投入值得。',author:'同一句“追求热爱”，背后的试错预算可能完全不同。',tag:'学校 · 阶层与试错成本'},
    {title:'选择有清晰职业路径的专业',wish:'我也向往可靠、有秩序的生活。',gain:'你能看见一条较清楚的就业路线。',cost:'画画变成要从课业里另外挤出的时间。',thin:'较可预测的开销让家人松了口气，你也暂时放下经济焦虑。',buffer:'生活更符合家人的预期；你开始分辨，安稳是谁的愿望。',author:'稳定本身不是错误，关键是你有没有看见其他路径。',tag:'学校 · 风险与教育期待'},
    {title:'先读一年，再申请转向',wish:'我需要更多信息，才能替未来决定。',gain:'你给自己保留了重新判断的机会。',cost:'转专业的门槛仍然存在，延期也会增加开销。',thin:'你查了规则，又给自己列了一张兼职计划。',buffer:'家庭能负担延期，但你仍要说服学校和家人接受绕路。',author:'“以后再选”也是选择，但未来的门不一定一直开着。',tag:'学校 · 制度与路径依赖'}]},
  {age:24,name:'工作',title:'会议结束后，还剩一件事。',scene:'你和同事一起完成了一个项目。\n新的机会来了：一个能被看见的提案，以及一份没人主动认领的协调工作。',question:'在这份工作里，你现在最想争取什么？',speaker:'主管，散会以后',voice:'「你沟通细，又让人放心。客户协调还是你来吧？」',context:{thin:'你刚攒下一点应急金，房租和给家里的补贴每月都要支出。',buffer:'生活暂时有缓冲，可以承担一段工作关系不稳定的时间。'},options:[
    {title:'争取做提案负责人',wish:'让我的想法被看见。',gain:'你获得介绍自己方案的机会。',cost:'你需要公开争取资源，也可能遭遇否定。',thin:'你保留现有岗位，一边额外准备提案，机会先消耗了休息。',buffer:'你拒绝一部分杂务，把精力放在方案上；同事并不都认同。',author:'表达野心不自动换来机会，资源分配也在起作用。',tag:'工作 · 可见度与评价权'},
    {title:'把协调工作做好',wish:'我喜欢让一群人顺利合作。',gain:'团队因为你的协调少了很多摩擦。',cost:'成果可能被归到团队名下，难以体现在晋升中。',thin:'熟悉的职责让收入可预期，但工作量慢慢超过岗位说明。',buffer:'你享受合作本身，也开始要求把贡献写进考核。',author:'维护关系是劳动。喜欢它，不意味着它可以一直不被计价。',tag:'工作 · 不可见劳动'},
    {title:'要求轮岗与明确署名',wish:'希望分工可以说清楚。',gain:'一部分隐形劳动被写到了台面上。',cost:'讨论暂时没有结论，有人觉得你把事情复杂化了。',thin:'你邀请同事一起提出建议，避免一个人承担全部风险。',buffer:'你能承受谈判失败，但还需要同事共同改变规则。',author:'把问题说出来是开始，规则改变还需要集体支持。',tag:'工作 · 制度与协同行动'}]},
  {age:29,name:'亲密关系',title:'两个人的未来，写在哪里？',scene:'伴侣收到另一座城市的工作邀请。\n你在这里刚建立起自己的合作网络。两张地图被摊在同一张桌上。',question:'此刻你真正向往的是哪一种生活？',speaker:'伴侣，认真地商量',voice:'「我们总要有一个人调整。我也怕错过这次机会。」',context:{thin:'两地房租和频繁往返，会明显压缩你们的储蓄。',buffer:'你们能暂时负担两地生活，但金钱不能补上所有缺席的日常。'},options:[
    {title:'一起去新的城市',wish:'我想和这个人一起生活。',gain:'你们继续分享具体的日常。',cost:'你需要在陌生地方重建工作和朋友网络。',thin:'你先找一份能覆盖房租的工作，原来的计划向后挪了。',buffer:'你有时间寻找机会，也要面对暂时依赖对方的感觉。',author:'为爱迁移可以是主动选择，关键是调整责任是否总落在一边。',tag:'关系 · 流动与机会成本'},
    {title:'留在这里，尝试异地',wish:'我想守住正在长出来的生活。',gain:'你保留了自己的工作和支持网络。',cost:'关系需要承受距离、不确定与额外沟通。',thin:'你们减少见面次数，把有限的钱留给重要往返。',buffer:'你们可以常见面，但无法预订彼此每一次需要陪伴的时刻。',author:'独立不等于不需要他人，坚持也可能伴随失落。',tag:'关系 · 自主与依恋'},
    {title:'谈一个六个月的共同计划',wish:'我不想一个人替两个人做决定。',gain:'你们把各自的损失和愿望一起摊开。',cost:'临时安排有期限，到时仍可能无法两全。',thin:'你们列出费用上限，约定双方轮流承担往返。',buffer:'你们有条件尝试更多安排，但必须持续协商。',author:'协商需要对等的发言权，也需要可执行的条件。',tag:'关系 · 共同决策'}]},
  {age:35,name:'此刻',title:'那个空出来的星期六。',scene:'你终于有了一个没有被安排的下午。\n手机里有家人的消息、朋友的邀约，还有一个很久没打开的创作文件夹。',question:'如果这个下午只属于你，你想把它交给什么？',speaker:'你自己，或者那些已经住进心里的声音',voice:'「我是不是应该先做一点有用的事？」',context:{thin:'这周你已经很累。休息、兼职和关系都在等待同一段时间。',buffer:'你可以暂时放下生计，但“不能浪费时间”的感觉没有一起消失。'},options:[
    {title:'重新打开创作文件夹',wish:'我想继续那个未完成的东西。',gain:'作品多了一小部分，你重新感到了投入。',cost:'一些消息没有及时回复，家务也还在那里。',thin:'你把创作限定在两小时内，给接下来的工作留一点体力。',buffer:'你允许自己没有产出地试了很久，仍偶尔想证明这段时间值得。',author:'热爱也可能被变成新的绩效，它是否允许你暂时做得不好？',tag:'此刻 · 生产力的内化'},
    {title:'去见一个想念的人',wish:'有些连接，是我自己想维系的。',gain:'你们好好说了一次话。',cost:'独处和创作需要另找一个时间。',thin:'你们选了不用花钱的散步，承认彼此最近都有些吃力。',buffer:'你把手机放到一边，不把见面变成一个“有效安排”。',author:'关系不全是外界束缚，它也可以是你主动选择的自我组成。',tag:'此刻 · 连接与主体性'},
    {title:'今天，什么都不证明',wish:'我只想休息。',gain:'身体慢慢放松了下来。',cost:'事情没有消失，内疚也没有立即停止。',thin:'你给兼职消息设了晚一点的提醒，停下仍有经济成本。',buffer:'你拥有休息的空间，开始练习不为它寻找正当理由。',author:'休息不该是奖励，但不同的人能停下来的条件并不相同。',tag:'此刻 · 时间与休息权'}]}
];

let state = {screen:'home', background:'thin', step:0, wish:null, records:[], revealed:false, rewrite:null, reflection:'', phrase:'', custom:null};
let audio = null;
try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved && Array.isArray(saved.records)) state = {...state, ...saved}; } catch {}

const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const currentOptions = stage => state.custom && stage === STAGES[0] ? [...stage.options, state.custom] : stage.options;
const optionAt = (stage,index) => currentOptions(stage)[index] || stage.options[0];
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));document.querySelector('#save-state').textContent='已保存 · 本机';}catch{document.querySelector('#save-state').textContent='仅本次体验';}}
function notify(message){toast.textContent=message;toast.style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.style.display='none',3200)}
function transition(){render();app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function makeCustom(){const phrase=state.phrase.trim();if(!phrase)return null;const title=/家|照顾|陪/.test(phrase)?'让照护不再只落在我身上':/画|写|创作|梦/.test(phrase)?'为这件想做的事留出时间':/爱|关系|朋友/.test(phrase)?'把重要的关系带进决定里':'把这句话留给自己';return {title,wish:`我想保留：${phrase.slice(0,48)}`,gain:'你把一句尚未有位置的话，放进了人生选项。',cost:'这条路没有现成模板，需要你和别人协商条件。',thin:'你从一件可执行的小事开始，把愿望拆成可以被支持的请求。',buffer:'你有空间试一次，但仍要面对“这值得吗”的追问。',author:'这是由你的原话生成的第四个选项。翻译可以被修改，决定权仍在你手里。',tag:'你的输入 · 可被修改的愿望'};}

function drawAtlas(){const canvas=document.querySelector('#atlas-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),d=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*d;canvas.height=h*d;ctx.scale(d,d);let t=0;function frame(){ctx.clearRect(0,0,w,h);ctx.fillStyle='#e2ddcf';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#c0baac';ctx.lineWidth=1;for(let x=0;x<w;x+=28){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=28){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='#b63a2b88';ctx.setLineDash([2,7]);ctx.beginPath();ctx.arc(w*.52,h*.5,Math.min(w,h)*.32,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);const cx=w*.52,cy=h*.5;ctx.fillStyle='#30342f';ctx.beginPath();ctx.ellipse(cx,cy-75,30,34,0,0,Math.PI*2);ctx.fill();ctx.fillRect(cx-48,cy-42,96,150);ctx.strokeStyle='#b63a2b';ctx.lineWidth=1.5;const lines=[[.12,.18,cx-20,cy-18],[.86,.2,cx+24,cy-16],[.1,.73,cx-34,cy+65],[.85,.78,cx+34,cy+78]];lines.forEach((l,i)=>{const ax=w*l[0],ay=h*l[1];ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(l[2],l[3]);ctx.stroke();ctx.fillStyle='#b63a2b';ctx.beginPath();ctx.arc(ax,ay,3,0,7);ctx.fill();ctx.font='14px serif';ctx.fillText(['要懂事','为你好','别任性','有用的人'][i],ax+(i%2?0:-10),ay-8)});ctx.fillStyle='#b63a2b';ctx.font='22px serif';ctx.fillText('我',cx-8,cy+25);t+=.015;requestAnimationFrame(frame)}frame()}

function renderHome(){app.innerHTML=`<section class="home"><div class="home-copy"><div class="eyebrow">AN INTERACTIVE GAME ABOUT BECOMING</div><h1>成为<br><em>自己。</em></h1><p class="lead">你会长大，会做选择，会被夸奖“懂事”。直到有一天，你翻到人生的背面，才发现那里还有别人的笔迹。</p><button class="primary" data-action="prologue">开始这一生 <span>↗</span></button>${state.records.length?'<button class="secondary" data-action="resume">继续上次的人生</button>':''}<div class="meta"><span>约 5—7 分钟</span><span>五个时刻</span><span>一次重新落笔</span></div></div><div class="atlas"><canvas id="atlas-canvas" aria-label="一张被红线牵引的人形纸片"></canvas><div class="atlas-caption"><span>人的轮廓 / 尚未定稿</span><span class="red">不是命运图谱</span></div></div></section><div class="home-note"><strong>你以为是“我的选择”，<br>有多少其实是别人替你写好的？</strong><div>先听见自己的心愿，再走进现实的条件。最后，把人生翻到背面。这里没有分数，只有一页尚未结束的问题：我还想把什么，写回自己的手里？</div></div>`;drawAtlas()}
function renderPrologue(){app.innerHTML=`<section class="prologue"><div class="eyebrow red">序章 / 00 岁 · 出生</div><h1>你还没学会说“我”，<br>世界已经开始称呼你。</h1><p>这一次，你走进“林”的生活：一个在县城长大的女性。你将经历五个虚构切片。起点不是人格，却会改变同一选择的代价。</p><div class="condition-grid"><button class="condition ${state.background==='thin'?'selected':''}" data-action="background" data-value="thin"><b>需要自己兜底</b>家人关心你，但能提供的经济支持有限。意外和试错，需要从自己的时间里支付。</button><button class="condition ${state.background==='buffer'?'selected':''}" data-action="background" data-value="buffer"><b>拥有一些缓冲</b>家里可以支持一段试错。经济压力小一些，情感义务与外界期待依然存在。</button></div><div class="seed"><label for="phrase">给这一生一句想保留的话……</label><textarea id="phrase" maxlength="70" placeholder="例如：我想保留周末画画的时间，也想照顾好家人。">${escapeHTML(state.phrase)}</textarea><small>这句话只在本机处理，会变成一个可修改的第四选项。</small></div><div class="start-actions"><button class="primary" data-action="start">让故事开始 <span>→</span></button><button class="secondary" data-action="quick">3 分钟演示模式</button></div></section>`}
function progress(){return `<ol class="progress" aria-label="故事进度">${STAGES.map((s,i)=>`<li class="${i===state.step?'active':i<state.step?'done':''}">${String(i+1).padStart(2,'0')}<span>${s.name} / ${s.age} 岁</span></li>`).join('')}</ol>`}
function choiceList(stage,mode){return `<div class="choice-list">${currentOptions(stage).map((o,i)=>`<button class="choice" data-action="${mode}" data-value="${i}"><span class="letter">${i===3?'✦':String.fromCharCode(65+i)}</span><span><strong>${escapeHTML(o.title)}</strong><small>${escapeHTML(mode==='wish'?o.wish:'我决定这样做。')}${i===3?' · 你的句子':''}</small></span></button>`).join('')}</div>`}
function actionChoiceList(stage){const chosen=optionAt(stage,state.wish);return `<button class="choice heart-choice" data-action="follow-wish"><span class="letter">♥</span><span><strong>就沿着这个心意走</strong><small>${escapeHTML(chosen.title)} · ${escapeHTML(chosen.wish)}</small></span></button><div class="choice-separator"><span>或者，改变你的心意</span></div>${choiceList(stage,'actual')}`}
function renderPlay(){const stage=STAGES[state.step],record=state.records[state.step];let body;if(state.screen==='wish')body=`<div class="phase">第一遍 · 只问心愿</div><h2 class="question">${stage.question}</h2>${choiceList(stage,'wish')}<p class="eyebrow">先别急着权衡。接下来，你会看见现实里的条件。</p>`;else if(state.screen==='choice')body=`<div class="phase">第二遍 · 把现实放回画面</div><div class="wish">刚才，你想要的是<br><strong>${escapeHTML(optionAt(stage,state.wish).wish)}</strong></div><div class="voice"><label>${stage.speaker}</label><p>${stage.voice}</p><small>${stage.context[state.background]}</small></div><h2 class="question">现在，你会怎么做？</h2>${actionChoiceList(stage)}`;else{const o=optionAt(stage,record.actual);body=`<div class="phase">这一页 · 你确实走过</div><div class="aftermath"><h2>${o.title}</h2><p>${o[state.background]}</p><div class="tradeoffs"><div><label>你得到的</label>${o.gain}</div><div><label>你也承担着</label>${o.cost}</div></div><div class="price-note">${record.wish===record.actual?'你把最初的心意带进了现实。现在，试着感受：这就是你想要的风景吗？它的价格，你愿意支付吗？':'你改变了最初的心意。也许是放手，也许是为了另一种风景支付了另一种价格。'}</div><button class="primary continue" data-action="next">${state.step===4?'把人生翻到背面':'继续长大'} <span>→</span></button></div>`}app.innerHTML=`<section class="play"><div class="demo-badge">${state.quick?'演示模式 · 3 分钟':'人生记录 · 进行中'}</div>${progress()}<div class="play-grid"><aside class="chapter"><div class="eyebrow">LIFE FRAGMENT / 0${state.step+1}</div><div class="age">${stage.age}<small>岁 / ${stage.name}</small></div><h1>${stage.title}</h1><p>${stage.scene}</p><div class="chapter-art">人生档案 / 林<br>起点：${state.background==='thin'?'需要自己兜底':'拥有一些缓冲'}<br>你不是在找最优解。你正在留下自己的笔迹。</div></aside><div>${body}</div></div></section>`}
function renderEnding(){const same=state.records.filter(r=>r.wish===r.actual).length;app.innerHTML=`<section class="ending"><div class="eyebrow red">THE OTHER SIDE / 人生的背面</div><h1>${state.revealed?'原来，一直不止<br>我一个人在落笔。':'这五次选择，<br>真的是我一个人写的吗？'}</h1><p class="ending-intro">五个时刻里，有 ${same} 次心愿与行动相遇。这个数字不是“做自己”的分数：顺从可能出于爱，坚持也可能出于焦虑。我们把两者并排放在这里，留给你自己读。</p>${state.revealed?'':'<button class="primary reveal" data-action="reveal">显影：看见选项背后的字 <span>↗</span></button>'}<div class="ledger ${state.revealed?'revealed':''}"><div class="ledger-head"><span>时刻</span><span>最初的心愿</span><span>现实中的选择</span><span>选项背后的字</span></div>${state.records.map(r=>{const s=STAGES[r.step],o=optionAt(s,r.actual);return `<div class="ledger-row"><div class="stage">${s.name}<small>${s.age} 岁</small></div><div>${optionAt(s,r.wish).title}</div><div>${o.title}</div><div class="margin-note">${state.revealed?`${o.author}<br><small>↳ ${o.tag}</small><br><button class="text-btn" data-action="rewrite" data-value="${r.step}">改写这一页 ↗</button>`:'<span class="hidden" aria-label="尚未显影的文字"></span>'}</div></div>`}).join('')}</div>${state.rewrite?rewritePanel():''}${state.revealed?`<div class="reflection"><div><div class="phase">下一页 / 尚未发生</div><h2>如果选项里没有我想要的，<br>我可以自己写一个吗？</h2><p>你不必永远在“接受”和“离开”之间作答。也许你需要的是一个愿意分担的人、一条允许回头的规则，或者一次不必解释的休息。</p></div><div><label class="eyebrow" for="reflection">写下你想增加的第四个选项</label><textarea id="reflection" maxlength="160" placeholder="我希望，在要求我变得勇敢之前……">${escapeHTML(state.reflection)}</textarea><div class="action-row"><button class="primary" data-action="export">带走这一页 <span>↓</span></button><button class="secondary" data-action="save">留在本机</button></div></div></div><div class="action-row"><button class="secondary" data-action="restart">换一组起点，再走一次</button><button class="secondary" data-action="about">阅读创作手记 ↗</button></div>`:''}</section>`}
function enhanceEnding(){if(!state.revealed)return;const ending=document.querySelector('.ending'),route=document.createElement('section');route.className='wish-route';route.innerHTML=`<div class="eyebrow red">THE HEART'S ROUTE / 如果完全按心意走</div><h2>这条路，会把你带到哪里？</h2><p>这不是一条更正确的路线。所有命运赠送的礼物，早已在暗中标好了价格；每个选择也都有自己的风景。逐格看一遍：如果五次都把最初的心愿带进现实，你会喜欢这条路吗？</p><div class="wish-route-grid">${state.records.map(r=>{const s=STAGES[r.step],o=optionAt(s,r.wish);return `<div class="wish-route-card"><b>${s.name}</b><small>顺着心意</small>${escapeHTML(o.title)}<br>${escapeHTML(o.gain)}<br><small>价格</small>${escapeHTML(o.cost)}</div>`}).join('')}</div><p class="route-question">没有免费的选择。要么放手，要么找到标签上没有写明的价格，并决定是否支付它。</p>`;ending.querySelector('.ledger').before(route);const h=ending.querySelector('.reflection h2'),p=ending.querySelector('.reflection p');if(h)h.innerHTML='西西弗知道山顶还会失去，<br>仍然选择把石头推上去。';if(p)p.textContent='幸福不来自没有代价，而来自你清楚自己正在做什么。斗争本身可以充实人的心灵；承担也不等于忍受一切，而是知道这一次的代价属于哪一种愿望，并决定它是否值得。如果答案是不值得，放手也是自主；如果值得，就去找到标签没有写明的价格，勇敢地支付它。'}
function rewritePanel(){const {step,option}=state.rewrite,s=STAGES[step],before=optionAt(s,state.records[step].actual),after=optionAt(s,option);return `<section class="counterfactual"><div class="phase">另一种可能 / ${s.age} 岁</div><h2>换一种选择，未必换来一个完美人生。</h2><div class="comparison"><div><label>你原来写下的</label><h3>${before.title}</h3><p>${before[state.background]}</p><p>得到：${before.gain}<br>代价：${before.cost}</p></div><div><label>你重新写下的</label><h3>${after.title}</h3><p>${after[state.background]}</p><p>得到：${after.gain}<br>代价：${after.cost}</p></div></div><p class="red">你愿意为这种结果承担代价吗？又有哪些代价，本来就不该只由你承担？</p></section>`}
function showAbout(){dialogContent.innerHTML=`<div class="eyebrow red">ARTIST'S NOTE / 创作手记</div><h2>成为自己，不是一道单选题。</h2><p>这是一款把“愿望—条件—行动—代价”拆开的互动叙事游戏。它不为你计算人格，也不预测命运；它让你看见一次选择同时拥有的私人愿望与现实条件。</p><h3>游戏如何工作</h3><p>你会先说出想要什么，再把现实放回画面。每一次行动都会留下视觉与文字痕迹。五个时刻之后，你可以显影那些藏在选项背后的期待，并重新改写任意一页。</p><p>所有选择和文字只保存在本机。没有云端社区，没有虚构的其他玩家数据，也没有实时生成模型替你判断。</p><div class="action-row"><button class="secondary" data-action="clear">删除本机进度与文字</button></div>`;dialog.showModal()}
function exportPage(){const c=document.createElement('canvas');c.width=1200;c.height=1500;const x=c.getContext('2d');x.fillStyle='#e9e4d8';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#bdb7aa';x.strokeRect(55,55,1090,1390);x.fillStyle='#b63a2b';x.font='18px sans-serif';x.fillText('BE MYSELF     一页尚未定稿的人生',90,110);x.fillStyle='#242622';x.font='72px serif';x.fillText('成为自己。',90,220);x.font='23px serif';x.fillText('那些落在我人生上的笔迹，我开始认得了。',90,280);x.font='17px sans-serif';x.fillStyle='#716f66';x.fillText(`虚构角色：林  /  ${state.background==='thin'?'需要自己兜底':'拥有一些缓冲'}`,90,330);let y=410;state.records.forEach(r=>{const s=STAGES[r.step];x.fillStyle='#b63a2b';x.font='20px serif';x.fillText(`${s.age} 岁 / ${s.name}`,90,y);x.fillStyle='#242622';x.font='23px serif';x.fillText(optionAt(s,r.actual).title,285,y);x.fillStyle='#716f66';x.font='16px sans-serif';x.fillText('心愿：'+optionAt(s,r.wish).title,285,y+32);x.strokeStyle='#c8c2b3';x.beginPath();x.moveTo(90,y+55);x.lineTo(1110,y+55);x.stroke();y+= ninetyNine();});function ninetyNine(){return 96}x.fillStyle='#b63a2b';x.font='19px sans-serif';x.fillText('下一页，尚未发生',90,930);x.fillStyle='#242622';x.font='27px serif';x.fillText('我可以给自己增加一个新的选项。',90,980);x.font='27px serif';let text=state.reflection.trim()||'我想改的，是我的选择，还是让选择如此艰难的条件？';let line='',yy=1060;for(const char of text){if(char==='\n'||x.measureText(line+char).width>980){x.fillText(line,90,yy);yy+=44;line=char==='\n'?'':char}else line+=char}if(line)x.fillText(line,90,yy);x.fillStyle='#716f66';x.font='16px sans-serif';x.fillText('互动叙事 · 原创虚构 · 无人格评分与命运预测',90,1380);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='be-myself-人生之书.png';a.click();notify('已生成你的书页图片。')},'image/png')}

document.addEventListener('click', event => {const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;const value=Number(button.dataset.value);if(action==='about'){showAbout();return}if(action==='prologue'){state.screen='prologue';transition();return}if(action==='background'){state.background=button.dataset.value;persist();renderPrologue();return}if(action==='start'||action==='quick'){state.phrase=(document.querySelector('#phrase')?.value||state.phrase).slice(0,70);state.custom=makeCustom();state.screen='wish';state.step=0;state.wish=null;state.records=[];state.revealed=false;state.rewrite=null;state.quick=action==='quick';persist();transition();return}if(action==='resume'){state.screen=state.records.length===5?'ending':'wish';state.step=state.records.length===5?4:state.records.length;transition();return}if(action==='wish'){state.wish=value;state.screen='choice';transition();return}if(action==='follow-wish'){state.records.push({step:state.step,wish:state.wish,actual:state.wish});state.screen='aftermath';persist();transition();return}if(action==='actual'){state.records.push({step:state.step,wish:state.wish,actual:value});state.screen='aftermath';persist();transition();return}if(action==='next'){state.step===4?state.screen='ending':(state.step++,state.wish=null,state.screen='wish');persist();transition();return}if(action==='reveal'){state.revealed=true;persist();transition();return}if(action==='rewrite'){state.rewrite={step:value,option:null};showRewrite(value);return}if(action==='rewrite-option'){state.rewrite.option=value;dialog.close();persist();transition();return}if(action==='restart'){state={...state,screen:'prologue',step:0,wish:null,records:[],revealed:false,rewrite:null,reflection:''};persist();transition();return}if(action==='save'){state.reflection=(document.querySelector('#reflection')?.value||'').slice(0,160);persist();notify('这一页已留在本机。');return}if(action==='export'){state.reflection=(document.querySelector('#reflection')?.value||'').slice(0,160);persist();exportPage();return}if(action==='clear'){localStorage.removeItem(STORAGE_KEY);state={screen:'home',background:'thin',step:0,wish:null,records:[],revealed:false,rewrite:null,reflection:'',phrase:'',custom:null};dialog.close();transition();notify('本机进度与文字已删除。')}});
document.addEventListener('input',event=>{if(event.target.id==='reflection')state.reflection=event.target.value.slice(0,160)});
function showRewrite(step){const s=STAGES[step],r=state.records[step];dialogContent.innerHTML=`<div class="eyebrow red">REWRITE / ${s.age} 岁 · ${s.name}</div><h2>如果再给你一次落笔的机会。</h2><p>当时你最想：${optionAt(s,r.wish).title}。<br>后来你选择：${optionAt(s,r.actual).title}。</p><p>现实条件仍然存在：${s.context[state.background]}</p><div class="choice-list">${s.options.map((o,i)=>i===r.actual?'':`<button class="choice" data-action="rewrite-option" data-value="${i}"><span class="letter">↗</span><span><strong>${o.title}</strong><small>看一看这一条路得到什么，又要付出什么。</small></span></button>`).join('')}</div>`;dialog.showModal()}
document.querySelector('#about').addEventListener('click',showAbout);document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
let soundOn=false;document.querySelector('#sound').addEventListener('click',async()=>{try{const AC=window.AudioContext||window.webkitAudioContext;if(!audio){const ctx=new AC(),gain=ctx.createGain();gain.gain.value=0;gain.connect(ctx.destination);[130.81,196,261.63].forEach((frequency,index)=>{const oscillator=ctx.createOscillator(),volume=ctx.createGain();oscillator.frequency.value=frequency;volume.gain.value=[.035,.015,.008][index];oscillator.connect(volume).connect(gain);oscillator.start()});audio={ctx,gain}}await audio.ctx.resume();soundOn=!soundOn;audio.gain.gain.setTargetAtTime(soundOn?.05:0,audio.ctx.currentTime,.3);document.querySelector('#sound').textContent=`声音 · ${soundOn?'开':'关'}`;document.querySelector('#sound').setAttribute('aria-pressed',String(soundOn))}catch{notify('当前浏览器无法启用声音，你可以继续无声体验。')}});
function render(){if(state.screen==='home')renderHome();else if(state.screen==='prologue')renderPrologue();else if(state.screen==='ending'){renderEnding();enhanceEnding()}else renderPlay()}
render();
